CREATE DATABASE correo;

CREATE TABLE envio (
	ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	NOMBRE_DESTINATARIO VARCHAR(255) NOT NULL,
	EMAIL_DESTINATARIO VARCHAR(255) NOT NULL,
	PROVINCIA_DESTINATARIO VARCHAR(255) NOT NULL,
	MENSAJE_DESTINATARIO VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
);